<script>
require([
    'jquery',
    'Magento_Catalog/js/product/list/toolbar'
], function($) {
    
    $.mage.productListToolbarForm.prototype.changeUrl = function (paramName, paramValue, defaultValue) {
        var decode = window.decodeURIComponent;
        var urlPaths = this.options.url.split('?'),
            baseUrl = urlPaths[0],
            urlParams = urlPaths[1] ? urlPaths[1].split('&') : [],
            paramData = {},
            parameters;
        for (var i = 0; i < urlParams.length; i++) {
            parameters = urlParams[i].split('=');
            paramData[decode(parameters[0])] = parameters[1] !== undefined
                ? decode(parameters[1].replace(/\+/g, '%20'))
                : '';
        }
        paramData[paramName] = paramValue;
        if (paramValue == defaultValue) {
            delete paramData[paramName];
        }
        paramData = $.param(paramData);
        
        var ajaxUrl = baseUrl + (paramData.length ? '?' + paramData : '');
        this.ajaxLoad.call(this, ajaxUrl);
    };
        
    $.mage.productListToolbarForm.prototype.ajaxLoad = function(ajaxUrl) {
        if (window.productListAjaxLoading) {
            return;
        }
        window.productListAjaxLoading = true;
        $.ajax({
            url: ajaxUrl,
            showLoader: true
        }).done(function(response) {
            $(document).find('#maincontent > .columns').replaceWith($(response).find('#maincontent > .columns'));
            $(document).find('#maincontent > .columns').trigger('contentUpdated');
        }).fail(function(response) {
            var $messages = $('[data-placeholder="messages"]');
            if ($messages.length) {
                $messages.append($('<div>', {class: 'message error message-error', 'data-ui-id': 'message-error'}).append($('<div>').html('An error occured whilst filtering the products.')));
                $('html,body').animate({scrollTop: $messages.offset().top});
            }
        }).always(function(){
            window.productListAjaxLoading = false;
        });
    };
    
    $(document).on('click', '.block.filter a', function(e) {
        e.preventDefault();
        $.mage.productListToolbarForm.prototype.ajaxLoad.call(this, $(this).attr('href'));
    });
});
</script>